# https://stackoverflow.com/questions/714063/importing-modules-from-parent-folder
# Please edit as needed, my Dev setup skills are lacking at best.
.PHONY: setup
setup: 
	virtualenv -p python3 venv
	source venv/bin/activate
	pip install -e .
	pip install -r requirements.txt

